% Created by D.B. Rowe
% Compute DAN directional means filtered image
% Uses 5x5 DAN filter

% Useage is
% %3D data loaded
% function [IDAN] = MyFilterDAN(I);

function [IDAN] = MyFilterDAN(I);

[ny,nx,n]=size(I);

Idist=zeros(8,1); IDAN=I;%zeros(ny,nx,n);
for t=1:n%
    %[t,n]
    for j=1:ny%%
        for i=1:nx%%%
            if (j>=3)&&(j<=ny-2)&&(i>=3)&&(i<=nx-2)%%%% Limit to 3rd in
                for nbrhd=1:8%%%%%
                    if (nbrhd==1)%%%%%% N:2,3,4,7,8,9
                        Idist(nbrhd,1)=...
                            (I(j-2,i-1,t)-I(j,i,t))^2+...
                            (I(j-2,i,t)  -I(j,i,t))^2+...
                            (I(j-2,i+1,t)-I(j,i,t))^2+...
                            (I(j-1,i-1,t)-I(j,i,t))^2+...
                            (I(j-1,i,t)  -I(j,i,t))^2+...
                            (I(j-1,i,t)  -I(j,i,t))^2;
                    elseif(nbrhd==2)%%%%%% NE:4,5,8,9,10,13
                        Idist(nbrhd,1)=...
                            (I(j-2,i+1,t)-I(j,i,t))^2+...
                            (I(j-2,i+2,t)-I(j,i,t))^2+...
                            (I(j-1,i,t)  -I(j,i,t))^2+...
                            (I(j-1,i+1,t)-I(j,i,t))^2+...
                            (I(j-1,i+2,t)-I(j,i,t))^2+...
                            (I(j,i+1,t)  -I(j,i,t))^2;
                    elseif(nbrhd==3)%%%%%% E:9,10,13,14,18,19
                        Idist(nbrhd,1)=...
                            (I(j-1,i+1,t)-I(j,i,t))^2+...
                            (I(j-1,i+2,t)-I(j,i,t))^2+...
                            (I(j,i+1,t)  -I(j,i,t))^2+...
                            (I(j,i+2,t)  -I(j,i,t))^2+...
                            (I(j+1,i+1,t)-I(j,i,t))^2+...
                            (I(j+1,i+2,t)-I(j,i,t))^2;
                    elseif(nbrhd==4)%%%%%% SE:13,17,18,19,23,24
                        Idist(nbrhd,1)=...
                            (I(j,i+1,t)  -I(j,i,t))^2+...
                            (I(j+1,i,t)  -I(j,i,t))^2+...
                            (I(j+1,i+1,t)-I(j,i,t))^2+...
                            (I(j+2,i-1,t)-I(j,i,t))^2+...
                            (I(j+2,i,t)  -I(j,i,t))^2+...
                            (I(j+2,i+1,t)-I(j,i,t))^2;
                    elseif(nbrhd==5)%%%%%% S:16,17,18,21,22,23
                        Idist(nbrhd,1)=...
                            (I(j+1,i-1,t)-I(j,i,t))^2+...
                            (I(j+1,i,t)  -I(j,i,t))^2+...
                            (I(j+1,i+1,t)-I(j,i,t))^2+...
                            (I(j+2,i-1,t)-I(j,i,t))^2+...
                            (I(j+2,i,t)  -I(j,i,t))^2+...
                            (I(j+2,i+1,t)-I(j,i,t))^2;
                    elseif(nbrhd==6)%%%%%% SW:12,15,16,17,20,21
                        Idist(nbrhd,1)=...
                            (I(j,i-1,t)  -I(j,i,t))^2+...
                            (I(j+1,i-2,t)-I(j,i,t))^2+...
                            (I(j+1,i-1,t)-I(j,i,t))^2+...
                            (I(j+1,i,t)  -I(j,i,t))^2+...
                            (I(j+2,i-2,t)-I(j,i,t))^2+...
                            (I(j+2,i-1,t)-I(j,i,t))^2;
                    elseif(nbrhd==7)%%%%%% W:6,7,11,12,15,16
                        Idist(nbrhd,1)=...
                            (I(j-1,i-2,t)-I(j,i,t))^2+...
                            (I(j-1,i-1,t)-I(j,i,t))^2+...
                            (I(j,i-2,t)  -I(j,i,t))^2+...
                            (I(j,i-1,t)  -I(j,i,t))^2+...
                            (I(j+1,i-2,t)-I(j,i,t))^2+...
                            (I(j+1,i-1,t)-I(j,i,t))^2;
                    elseif(nbrhd==8)%%%%%% NW:1,2,6,7,8,12
                        Idist(nbrhd,1)=...
                            (I(j-2,i-2,t)-I(j,i,t))^2+...
                            (I(j-2,i-1,t)-I(j,i,t))^2+...
                            (I(j-1,i-2,t)-I(j,i,t))^2+...
                            (I(j-1,i-1,t)-I(j,i,t))^2+...
                            (I(j-1,i,t)-I(j,i,t))^2+...
                            (I(j,i-1,t)-I(j,i,t))^2;
                    end%%%%%%
                end%%%%%
                if    (min(Idist)==Idist(1,1))%%%%%% N:2,3,4,7,8,9
                    IDAN(j,i,t)=mean([I(j-2,i-1,t),I(j-2,i,t),I(j-2,i+1,t),...
                        I(j-1,i-1,t),I(j-1,i,t),I(j-1,i,t)]);
                elseif(min(Idist)==Idist(2,1))%%%%%% NE:4,5,8,9,10,13
                    IDAN(j,i,t)=mean([I(j-2,i+1,t),I(j-2,i+2,t),I(j-1,i,t),...
                        I(j-1,i+1,t),I(j-1,i+2,t),I(j,i+1,t)]);
                elseif(min(Idist)==Idist(3,1))%%%%%% E:9,10,13,14,18,19
                    IDAN(j,i,t)=mean([I(j-1,i+1,t),I(j-1,i+2,t),I(j,i+1,t),...
                        I(j,i+2,t),I(j+1,i+1,t),I(j+1,i+2,t)]);
                elseif(min(Idist)==Idist(4,1))%%%%%% SE:13,17,18,19,23,24
                    IDAN(j,i,t)=mean([I(j,i+1,t),I(j+1,i,t),I(j+1,i+1,t),...
                        I(j+2,i-1,t),I(j+2,i,t),I(j+2,i+1,t)]);
                elseif(min(Idist)==Idist(5,1))%%%%%% S:16,17,18,21,22,23
                    IDAN(j,i,t)=mean([I(j+1,i-1,t),I(j+1,i,t),I(j+1,i+1,t),...
                        I(j+2,i-1,t),I(j+2,i,t),I(j+2,i+1,t)]);
                elseif(min(Idist)==Idist(6,1))%%%%%% SW:12,15,16,17,20,21
                    IDAN(j,i,t)=mean([I(j,i-1,t),I(j+1,i-2,t),I(j+1,i-1,t),...
                        I(j+1,i,t),I(j+2,i-2,t),I(j+2,i-1,t)]);
                elseif(min(Idist)==Idist(7,1))%%%%%% W:6,7,11,12,15,16
                    IDAN(j,i,t)=mean([I(j-1,i-2,t),I(j-1,i-1,t),I(j,i-2,t),...
                        I(j,i-1,t),I(j+1,i-2,t),I(j+1,i-1,t)]);
                elseif(min(Idist)==Idist(8,1))%%%%%% NW:1,2,6,7,8,12
                    IDAN(j,i,t)=mean([I(j-2,i-2,t),I(j-2,i-1,t),I(j-1,i-2,t),...
                        I(j-1,i-1,t),I(j-1,i,t),I(j,i-1,t)]);
                end%%%%%%
            end%%%%
        end%%%
    end%%
end%






